name: Space2Slash
main: ru.nukkit.space2slash.Space2Slash
version: "0.0.1"
api: ["1.0.0"]
load: POSTWORLD
author: fromgate, nukkit.ru, pcbeard
description: Allows to type spaces twice instead of slash when typing commands
commands:
  history:
    description:  Prints command history
    usage: "/history"
